---
 - hosts: all
   tasks:
   - name: Creating MicroShift Toml file
     copy:
       dest: "{{ microshift_local }}/rhde-microshift.toml"
       content: |
         name = "rhde-microshift"
         description = "RHDE Microshift Image"
         version = "1.0.0"
         modules = []
         groups = []
         [[packages]]
         name = "microshift"
         version = "*"
         [[packages]]
         name = "openshift-clients"
         version = "*"
         [[packages]]
         name = "git"
         version = "*"
         [[packages]]
         name = "iputils"
         version = "*"
         [[packages]]
         name = "bind-utils"
         version = "*"
         [[packages]]
         name = "net-tools"
         version = "*"
         [[packages]]
         name = "iotop"
         version = "*"
         [[packages]]
         name = "redhat-release"
         version = "*"
         [customizations]
         [customizations.services]
         enabled = ["microshift"]
              
   - name: Push blueprint to composer
     shell: composer-cli blueprints push "{{ microshift_local }}"/rhde-microshift.toml
     become: yes

   - name: Start compose of blueprint image
     shell: composer-cli compose start-ostree rhde-microshift rhel-edge-container| cut -f2 -d" "
     become: yes 
     register: compose_uuid
     
   - name: Check for compose to be completed
     shell: composer-cli compose status | grep "{{ compose_uuid }}"
     register: result
     until: result.stdout.find("FINISHED") != -1
     retries: 24
     delay: 300
     become: yes
     
     
     
