---
 - hosts: all
   tasks:
   - name: check if subman can configure repos
     ansible.builtin.shell:
       cmd: subscription-manager config | grep -i 'manage_repos = [0]'
     register: subman_repo_control
     changed_when: false
     check_mode: false
     failed_when: false

